#!/usr/bin/env bash
# script to permanently redirect
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
