#!/usr/bin/env bash
# creates custom 404 html page contaning a string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "47s|.*| \n\terror_page 404 /error404.html;\n|" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
