#!/usr/bin/env bash
# Script that gives information about the "bestschool" file
fl=bestschool
if [ -e $fl ]; then
   echo "bestschool file exists"
   if [ -s $fl ]; then
      echo "bestschool file is not empty"
   else
      echo "bestschool file is empty"
   fi
   if [ -f $fl ]; then
      echo "bestschool is a regular file"
   fi
else
	echo "bestschool file does not exist"
fi
